/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function DonutModel(props) {
  const { nodes, materials } = useGLTF("./models/donutcmp.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sprinkle.geometry}
        material={materials.Sprinkles}
        position={[0.06, 0, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Donut.geometry}
        material={materials["Material.003"]}
        position={[0, 1, 0]}
        rotation={[Math.PI / 2, -0.97, 0]}
        scale={17}
      >
        <group
          position={[0.02, 0.01, -0.04]}
          rotation={[-1.15, -1.04, 1.72]}
          scale={[0.06, 0.08, 0.06]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials.BlueCandy}
            position={[0, 0.93, 0]}
            scale={[1, 0.71, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder.geometry}
            material={materials.BlueCandy}
            position={[0, 0.07, 0]}
            scale={[1, 0.71, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003.geometry}
            material={materials.BlueCandy}
            position={[0, 0.36, 0]}
            scale={[1, 0.71, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002.geometry}
            material={materials.BlueCandy}
            position={[0, 0.21, 0]}
            scale={[1, 0.71, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder005.geometry}
            material={materials.BlueCandy}
            position={[0, 0.64, 0]}
            scale={[1, 0.71, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004.geometry}
            material={materials.BlueCandy}
            position={[0, 0.5, 0]}
            scale={[1, 0.71, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006.geometry}
            material={materials.BlueCandy}
            position={[0, 0.79, 0]}
            scale={[1, 0.71, 1]}
          />
        </group>
        <group
          position={[0.07, 0, 0.03]}
          rotation={[-Math.PI / 2, 0, 0.97]}
          scale={[0.05, 0.06, 0.05]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LegShape.geometry}
            material={materials["default"]}
          />
        </group>
        <group
          position={[-0.03, 0, 0.04]}
          rotation={[0.49, 0.12, -0.4]}
          scale={[-0.06, -0.08, -0.06]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder007.geometry}
            material={materials.BlueCandy}
            position={[0, 0.07, 0]}
            scale={[1, 0.71, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder008.geometry}
            material={materials.BlueCandy}
            position={[0, 0.21, 0]}
            scale={[1, 0.71, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder009.geometry}
            material={materials.BlueCandy}
            position={[0, 0.36, 0]}
            scale={[1, 0.71, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder011.geometry}
            material={materials.BlueCandy}
            position={[0, 0.64, 0]}
            scale={[1, 0.71, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010.geometry}
            material={materials.BlueCandy}
            position={[0, 0.5, 0]}
            scale={[1, 0.71, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder013.geometry}
            material={materials.BlueCandy}
            position={[0, 0.93, 0]}
            scale={[1, 0.71, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder012.geometry}
            material={materials.BlueCandy}
            position={[0, 0.79, 0]}
            scale={[1, 0.71, 1]}
          />
        </group>
        <group
          position={[0.05, 0, 0.06]}
          rotation={[-Math.PI / 2, 0, 0.97]}
          scale={[0.05, 0.06, 0.05]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LegShape001.geometry}
            material={materials["default"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus001.geometry}
          material={materials.Icing}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus001_1.geometry}
          material={materials.Sprinkles}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Eye.geometry}
          material={materials["Material.001"]}
          position={[-0.03, 0, -0.05]}
          rotation={[-Math.PI / 2, 0, 0.8]}
          scale={[0.04, 0.06, 0.04]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.EyeBall.geometry}
            material={materials["Material.006"]}
            position={[-0.03, 0.21, 0.02]}
            rotation={[0, 0, 0.2]}
            scale={[1.68, 1.03, 1.67]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Eyelash1.geometry}
              material={materials["Material.008"]}
              position={[-0.06, 0.06, 0.01]}
              rotation={[0, 0, 0.37]}
              scale={[0.1, 0.16, 0.1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Eyelash2.geometry}
              material={materials["Material.008"]}
              position={[0, 0.09, 0.01]}
              scale={[0.1, 0.16, 0.1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Eyelash3.geometry}
              material={materials["Material.008"]}
              position={[0.06, 0.07, 0.01]}
              rotation={[0, 0, -0.37]}
              scale={[0.1, 0.16, 0.1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Iris.geometry}
              material={materials["Material.007"]}
              position={[0, 0, 0.03]}
              scale={[0.69, 0.7, 0.7]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere_1.geometry}
                material={materials["Material.008"]}
                position={[0, 0, 0.05]}
                scale={1.43}
              />
            </mesh>
          </mesh>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Eye2.geometry}
          material={materials["Material.001"]}
          position={[-0.05, 0, -0.01]}
          rotation={[Math.PI / 2, 0, -1.15]}
          scale={[-0.04, -0.06, -0.04]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.EyeBall001.geometry}
            material={materials["Material.006"]}
            position={[-0.03, 0.2, 0]}
            rotation={[0, 0, 0.2]}
            scale={[1.68, 1.03, 1.67]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Eyelash1001.geometry}
              material={materials["Material.008"]}
              position={[-0.06, 0.06, 0.01]}
              rotation={[0, 0, 0.37]}
              scale={[0.1, 0.16, 0.1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Eyelash2001.geometry}
              material={materials["Material.008"]}
              position={[0, 0.09, 0.01]}
              scale={[0.1, 0.16, 0.1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Eyelash3001.geometry}
              material={materials["Material.008"]}
              position={[0.06, 0.07, 0.01]}
              rotation={[0, 0, -0.37]}
              scale={[0.1, 0.16, 0.1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Iris001.geometry}
              material={materials["Material.007"]}
              position={[0, 0, 0.03]}
              scale={[0.69, 0.7, 0.7]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere001_1.geometry}
                material={materials["Material.008"]}
                position={[0, 0, 0.05]}
                scale={1.43}
              />
            </mesh>
          </mesh>
        </mesh>
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/donutcmp.glb");
