/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 monkeycmp.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function MonkeyModel(props) {
  const { nodes, materials } = useGLTF("./models/monkeycmp.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Suzanne.geometry} material={materials["default"]} />
    </group>
  );
}

useGLTF.preload("./models/monkeycmp.glb");
